fix: execute script after dom nodes are ready
mdn/to-do-notifications pull request #24
Opened 2022-08-15 13:42 UTC by aliasliao

PR https://github.com/mdn/to-do-notifications/pull/22 causes a runtime error and makes the app completely unusable.
This pr just reverts it.

<img width="737" alt="image" src="https://user-images.githubusercontent.com/22636233/184646602-3fce346e-6444-49a9-86fe-5e808b3af76a.png">

2022-08-15 14:01 UTC, teoli2003 requested changes
This is not the correct fix. The correct fix is to read the UI elements, and performing the `Notification` test, inside the `window.onload` handler rather than before.

Do you want to do the change?

2022-08-16 02:36 UTC, aliasliao commented on scripts/todo.js
> -const newItem = [
unused reference

2022-08-16 02:37 UTC, aliasliao commented on scripts/todo.js
> -const submit = document.getElementById('submit');
unused reference

2022-08-16 02:41 UTC, aliasliao commented
> This is not the correct fix. The correct fix is to read the UI elements, and performing the `Notification` test, inside the `window.onload` handler rather than before.
> 
> Do you want to do the change?

okay. Have committed the correct changes.

2022-08-16 05:51 UTC, teoli2003 requested changes
I've added a commit to clean the comments (that were sometimes outdated).
I've also fixed a bug in the `ordinal` function and moved more things inside the load handler.

There are a few things to revert (.gitignore, and the position of `<script>` in the HTML.

After that, I think we should merge this and do follow-ups to fix problems we would have missed.

Great to see this being fixed.

2022-08-16 05:51 UTC, teoli2003 commented on .gitignore
> +.idea
This change shouldn't be in this PR.

2022-08-16 05:51 UTC, teoli2003 commented on index.html
> +  <script src="scripts/todo.js"></script>
We can revert this change now

2022-08-16 08:19 UTC, teoli2003 approved these changes
Let's merge this. Follow-ups in other PRs.

2022-08-16 08:19 UTC, merged

2022-08-16 08:26 UTC, teoli2003 commented
Thanks a lot!

Looks good to me.

Congratulations upon your first merged commit here! Welcome aboard! :tada: